### ISSUE TITLE
Swift compiler language level to 6

### ISSUE THREAD

**Issue by soomtong** [ensan-hcl/Typut#1]
Hi! I was wondering if you could give us a guide on how to build safely with swift 6 in Xcode 16.

I'm in the process of moving my code, which is currently in 5.x, to Swift language version 6 and would like some guidance from Typut. 

We are not in a hurry and will take a look at it when it's patched when you have time.

Thanks for your contributions esp. Input method!

**Comment by ensan-hcl** [comment]
Currently I'm not having the answer; I suspect it will be a hard job because the InputMethodKit lacks support for Swift Concurrency, and there's no indication that Apple will implement it. But if you manage to do that, I will be happy if you let me know :pray:

**Comment by soomtong** [comment]
Oh I get it. IMK is a really old framework, thanks. 
I won't be able to do it quickly, but I'll try. 💪🏼
